name: z_test
description: ZTest is a Quiz application for entertainment.

publish_to: "none"

version: 1.12.0+1

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_dotenv: ^5.1.0
  google_fonts: ^5.1.0
  http: ^1.1.0
  countdown_progress_indicator: ^0.1.2
  flutter_svg: ^2.0.9
  screenshot: ^2.1.0
  flutter_spinkit: ^5.2.0
  sqflite: ^2.3.0
  path: ^1.8.3
  get: ^4.6.6
  awesome_dialog: ^3.1.0
  path_provider: ^2.1.1
  just_audio: ^0.9.36
  image_picker: ^1.0.5


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
  - .env
  - assets/images/
  - assets/images/meme/
  - assets/icons/
  - assets/
  - assets/audio/

